# DATASOURCE (DataSourceAutoConfiguration & DatasourceProperties)
spring.datasource.url=jdbc:mysql://localhost:3306/dlsauwebtubedb
spring.datasource.username=root
spring.datasource.password=parakito

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update

# App Properties
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000

server.port=8081
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.address=0.0.0.0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jpellogo01@gmail.com
spring.mail.password=gjgtlenfknuevnuw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

openai.Key=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
spring.ai.openai.chat.options.model=gpt-4o-mini
